dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  app: deploydecide
  strategy: git
  api_key:
    secure: wJNZid0HvEHWlz1Rg5hj+mNECX2ENpFN/xTqcvDgtBG0xXpcE17OGW5pEM+Z2hlO7N0bqP/+vpsAtMIL9sQFLwv7VjZgu7rPr5U7IF0wE7CjNWXu16NPKFfnjPQb+jQO2vhgWfZkkXCrJrjkudh1bHMAp6bGO7TUoTHAamtLmW9fttBimN1vkRI83SLfmb38fUdsDUSlLnaPVvb2bcj6OoezO97uzyc+CxiAwAAwr5pYwuB8shFITmdyMkWg8WP0YBn9qpYzga1r4dVCV6BCneM21fKtVZY374LBS8IjbylvQsbtspdyexWCf4KYXJdjgoroPGetvhdP6e93y+g8zeM7DXuc7Qds9Q2jj1r23RvYM6jQahwY+iP/wHwY5UTkq8w5fIR4S3Anmt0ZA6Rn+bPcXUrs5rfedvcdDiG+edPQWFuJmAlwTH9PcfikP/JjVEnNW7tIHnzUQvpdozTDq2BpKTYWnJcXpltblyQImh6l6z6WMC53CX050hgW5ePF4B6YDZVJD7ycg7mcVu4vvQbVjCpKtpLB3zQweojJR5McPDb+JC3QZOnjNGxKBxUoBzPRJmIW0FOV8F4QUvVhjlFaVYdbUHGfpeUmN6cmq7M6i5eXzn919bWmBwym+Ck+bvEns/PtxjMIqUVZ4nZVRpccKQhwzgxNru4cUqPzKI4=
